global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "accounts"
    static_configs:
      - targets: ["localhost:8010"]
  - job_name: "middleaware"
    static_configs:
      - targets: ["localhost:8011"]
  - job_name: "accountsmetrics"
    static_configs:
      - targets: ["localhost:8010/metric"]
  - job_name: "middleawaremetrics"
    static_configs:
      - targets: ["localhost:8011/metric"]

